version: "3"

services:
  postgres:
    image: parkito/blocking_server_postgres:latest
    container_name: postgresql
    hostname: postgresql
    ports:
      - 5432:5432

  server:
    image: parkito/blocking_server:latest
    container_name: server
    hostname: server
    ports:
      - 9001:9001
    depends_on:
      - postgres